/**
 *
 * $Id$
 */
package depot.validation;

import depot.CoachClass;

/**
 * A sample validator interface for {@link depot.PassengerCoach}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PassengerCoachValidator {
	boolean validate();

	boolean validateClass(CoachClass value);
}
