/**
 *
 * $Id$
 */
package depot.validation;

import depot.Coach;
import depot.TrainType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link depot.Train}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TrainValidator {
	boolean validate();

	boolean validateCoach(EList<Coach> value);
	boolean validateName(String value);
	boolean validateType(TrainType value);
}
