<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="timetable" nsURI="http://mdse.org/pts/timetable" nsPrefix="timetable">
  <eClassifiers xsi:type="ecore:EClass" name="TimeTableSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" upperBound="-1"
        eType="#//Table" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrivals" upperBound="-1"
        eType="#//Arrival" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="station" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="departures" upperBound="-1"
        eType="#//Departure" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arrival" eSuperTypes="#//Juncture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Station"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Departure" eSuperTypes="#//Juncture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Station"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Juncture" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platform" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="train" lowerBound="1" eType="ecore:EClass ../../org.mdse.pts.depot/model/Depot.ecore#//Train"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weekday" lowerBound="1"
        eType="ecore:EEnum ../../org.mdse.pts.time/model/Time.ecore#//Weekday"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" eType="ecore:EClass ../../org.mdse.pts.time/model/Time.ecore#//Time"/>
  </eClassifiers>
</ecore:EPackage>
