/**
 *
 * $Id$
 */
package org.mdse.pts.schedule.validation;

import depot.Root;

import network.Network;

import org.eclipse.emf.common.util.EList;

import org.mdse.pts.schedule.TrainSchedule;

/**
 * A sample validator interface for {@link org.mdse.pts.schedule.Schedule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ScheduleValidator {
	boolean validate();

	boolean validateNetwork(Network value);
	boolean validateDepot(EList<Root> value);
	boolean validateTrains(EList<TrainSchedule> value);
}
