/**
 *
 * $Id$
 */
package org.mdse.pts.schedule.validation;

import org.eclipse.emf.common.util.EList;

import org.mdse.pts.schedule.Time;

import org.mdse.pts.time.Weekday;

/**
 * A sample validator interface for {@link org.mdse.pts.schedule.StartTime}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StartTimeValidator {
	boolean validate();

	boolean validateWeekdays(EList<Weekday> value);
	boolean validateTimestamps(EList<Time> value);
}
