/**
 *
 * $Id$
 */
package org.mdse.pts.schedule.validation;

import org.mdse.pts.network.Leg;
import org.mdse.pts.network.Station;

/**
 * A sample validator interface for {@link org.mdse.pts.schedule.Stop}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StopValidator {
	boolean validate();

	boolean validatePlatform(String value);
	boolean validateStoppedTime(int value);
	boolean validateVia(Leg value);
	boolean validateStation(Station value);
	boolean validateRotate(boolean value);
}
