/**
 *
 * $Id$
 */
package org.mdse.pts.schedule.validation;

import org.eclipse.emf.common.util.EList;

import org.mdse.pts.depot.Train;

import org.mdse.pts.schedule.StartTime;
import org.mdse.pts.schedule.Stop;

/**
 * A sample validator interface for {@link org.mdse.pts.schedule.TrainSchedule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TrainScheduleValidator {
	boolean validate();

	boolean validateTrain(Train value);
	boolean validateStarttimes(EList<StartTime> value);
	boolean validateStops(EList<Stop> value);
}
