/**
 *
 * $Id$
 */
package org.mdse.pts.timetable.validation;

import org.mdse.pts.network.Station;

/**
 * A sample validator interface for {@link org.mdse.pts.timetable.Arrival}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArrivalValidator {
	boolean validate();

	boolean validateOrigin(Station value);
}
