/**
 *
 * $Id$
 */
package org.mdse.pts.timetable.validation;

import org.mdse.pts.depot.Train;

import org.mdse.pts.time.Time;
import org.mdse.pts.time.Weekday;

/**
 * A sample validator interface for {@link org.mdse.pts.timetable.Juncture}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JunctureValidator {
	boolean validate();

	boolean validatePlatform(String value);
	boolean validateTrain(Train value);
	boolean validateWeekday(Weekday value);
	boolean validateTime(Time value);
}
