/**
 *
 * $Id$
 */
package network.validation;

import network.Station;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link network.Leg}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LegValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDistance(int value);
	boolean validateStations(EList<Station> value);
}
